# -*- coding: utf-8 -*-
"""halo_dunia.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1cHJsuAp93yzeTRkHUv-PD_ED9PQxN1Tc
"""

print('halo dunia!')
print('Belajar AI !')